
export const data =  [
    {
        "id": 1,
        "title": "iPhone 9",
        "description": "An apple mobile which is nothing like apple",
        "price": 549,
        "discountPercentage": 12.96,
        "rating": 4.69,
        "stock": 94,
        "brand": "Apple",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
        "images":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9h5fFpuVuDtR3cHU99XMONer0jwyZfLyR1w&usqp=CAU",
        "quantity":1,
    },
    {
        "id": 2,
        "title": "iPhone X",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "Apple",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
        "images": "https://i.ebayimg.com/images/g/2iQAAOSwI~JmE1Pk/s-l1600.jpg",
        "quantity":1,
    },
    {
        "id": 3,
        "title": "Samsung Universe 9",
        "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
        "price": 1249,
        "discountPercentage": 15.46,
        "rating": 4.09,
        "stock": 36,
        "brand": "Samsung",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
        "images": "https://i.ebayimg.com/images/g/G8oAAOSwdIlblX2q/s-l1200.jpg",
        "quantity":1,
    },
    {
        "id": 4,
        "title": "OPPOF19",
        "description": "OPPO F19 is officially announced on April 2021",
        "price": 280,
        "discountPercentage": 17.91,
        "rating": 4.3,
        "stock": 123,
        "brand": "OPPO",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
        "images":"https://i.ebayimg.com/images/g/IxQAAOSwX6NgbVwe/s-l1200.webp",
        "quantity":1,
    },
    {
        "id": 5,
        "title": "Huawei P30",
        "description": "Huaweis re-badged P30 Pro New Edition was officially unveiled yesterday in Germany",
        "price": 499,
        "discountPercentage": 10.58,
        "rating": 4.09,
        "stock": 32,
        "brand": "Huawei",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
        "images": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTTNOEczPoXVQ3Tbf4FW1dDKHJTJaeMfA5Rs5rMjrTh4CFuZ1NbRRfJF14dj8MYrT96Vf1KIHeAH0BuyVItxn3W9k85mhMc&usqp=CAE",
        "quantity":1,
    }
]